# src/main/resources/application.properties

# Application settings
app.api.url=https://jsonplaceholder.typicode.com/users
app.import.csv-file=classpath:employees.csv

# Logging configuration
logging.level.root=INFO